### ISSUE TITLE
Changes to verbose mode raising error

### ISSUE THREAD

**Issue by NicolasJJensen** [daveallie/entangler#6]
In commit 82f9eb8 26 days ago `initialize` in logger was changed to `verbose: false` from `verbose = false`

However when it is initialized in `lib/entangler/executor/base.rb:56` it's still based off the old `verbose = false`

`@logger ||= Entangler::Logger.new(log_outputs, @opts[:verbose])`
Should be changed to something like
`@logger ||= Entangler::Logger.new(log_outputs, verbose: @opts[:verbose])`test.rb

**Comment by daveallie** [comment]
Fixed in #7 - available in v[1.2.1](https://rubygems.org/gems/entangler/versions/1.2.1).
